import type { ProjectIdea } from "./schemas";

export const student = {
  name: "Aarav Sharma",
  field: "Computer Science · Final year",
  skills: ["Python", "React", "JavaScript", "SQL", "Basic ML"],
  interests: ["Healthcare", "AI", "Accessibility"],
  teamSize: 2,
  timeline: "4 weeks",
};

export const candidates: ProjectIdea[] = [
  {
    id: "carepath",
    title: "CarePath — Accessible Discharge Companion",
    problem: "After discharge, patients and caregivers struggle to understand medication changes, warning signs, and follow-up plans.",
    targetUser: "Patients with low health literacy and their family caregivers.",
    solution: "A clinician-configured companion that turns a verified discharge plan into plain-language, multilingual check-ins with an escalation path.",
    aiRole: "Constrained summarization and question routing over clinician-approved discharge content.",
    differentiator: "The product is scoped around the risky first 72 hours after discharge, with accessibility and clinician approval built into each answer.",
    technologies: ["React", "Python", "Postgres", "LLM API"],
    estimatedWeeks: "3–4 weeks",
    risk: "Requires careful safety boundaries and demo data.",
    scores: { originality: 76, impact: 88, aiNecessity: 79, technicalDepth: 82, feasibility: 73, skillMatch: 84, demoPotential: 90, scopeRisk: 44 },
  },
  {
    id: "signbridge",
    title: "SignBridge — Accessible Clinic Wayfinding",
    problem: "Deaf and hard-of-hearing patients often cannot access last-minute spoken changes in clinic queues.",
    targetUser: "Outpatient clinic visitors with hearing accessibility needs.",
    solution: "A real-time visual queue and care-instruction display that turns staff updates into clear, accessible cards.",
    aiRole: "Turns staff-authored updates into simplified, translated visual instructions.",
    differentiator: "Focuses on operational accessibility in a clinic rather than general translation.",
    technologies: ["React", "Node.js", "WebSockets", "LLM API"],
    estimatedWeeks: "3 weeks",
    risk: "Live queue integration is out of MVP scope.",
    scores: { originality: 71, impact: 82, aiNecessity: 68, technicalDepth: 74, feasibility: 86, skillMatch: 88, demoPotential: 83, scopeRisk: 32 },
  },
  {
    id: "medmap",
    title: "MedMap — Medication Conflict Explainer",
    problem: "Families cannot easily understand why medication schedules conflict after a care transition.",
    targetUser: "Caregivers managing several prescribed medications.",
    solution: "A visual schedule planner that flags timing conflicts and presents questions to take back to a pharmacist.",
    aiRole: "Explains schedule conflicts using a reviewed medicine data source; it does not diagnose or prescribe.",
    differentiator: "Designed for collaborative caregiver–pharmacist conversations, not clinical decision-making.",
    technologies: ["React", "Python", "SQL", "Rules Engine"],
    estimatedWeeks: "4–5 weeks",
    risk: "Drug information must come from an approved dataset.",
    scores: { originality: 68, impact: 85, aiNecessity: 61, technicalDepth: 78, feasibility: 62, skillMatch: 80, demoPotential: 78, scopeRisk: 57 },
  },
  {
    id: "accessnotes",
    title: "AccessNotes — Inclusive Lecture Action Extractor",
    problem: "Students with executive-function and accessibility needs lose key actions buried in long lecture material.",
    targetUser: "University students who need more accessible study workflows.",
    solution: "A source-grounded note workspace that turns uploaded lecture text into citation-linked actions and revision prompts.",
    aiRole: "Extracts actions only from the supplied content and links every generated point back to a source excerpt.",
    differentiator: "Prioritizes traceability and accessible pacing over generic note summarization.",
    technologies: ["React", "Python", "Vector Search", "LLM API"],
    estimatedWeeks: "3–4 weeks",
    risk: "Feature overlap with note-taking products is significant.",
    scores: { originality: 58, impact: 76, aiNecessity: 83, technicalDepth: 80, feasibility: 75, skillMatch: 86, demoPotential: 82, scopeRisk: 46 },
  },
  {
    id: "carevoice",
    title: "CareVoice — Symptom-to-Visit Prep",
    problem: "Patients forget important symptoms and questions before short follow-up appointments.",
    targetUser: "Patients preparing for a scheduled non-emergency follow-up visit.",
    solution: "A guided, non-diagnostic intake that produces a concise, editable appointment brief for the patient.",
    aiRole: "Groups patient-entered notes into a question checklist without giving medical advice.",
    differentiator: "A patient-owned preparation tool with explicit safety routing and no diagnosis claims.",
    technologies: ["React", "TypeScript", "Postgres", "LLM API"],
    estimatedWeeks: "2–3 weeks",
    risk: "Safety copy and emergency routing are essential.",
    scores: { originality: 65, impact: 78, aiNecessity: 72, technicalDepth: 67, feasibility: 90, skillMatch: 90, demoPotential: 85, scopeRisk: 25 },
  },
];

export const deathTest = [
  { category: "Originality attack", status: "warning", title: "Care coordination tools already exist", text: "Your differentiator needs to be the verified 72-hour discharge workflow—not broad care management." },
  { category: "AI necessity attack", status: "warning", title: "AI could become a decorative summary layer", text: "Constrain it to plain-language transformation and route uncertain questions to an approved escalation flow." },
  { category: "Feasibility attack", status: "critical", title: "Live hospital integration will sink the MVP", text: "Use a clinician-authored demo discharge packet. Do not promise EHR connectivity in four weeks." },
  { category: "Judge attack", status: "warning", title: "Safety boundary will be challenged", text: "Show refusal behavior, source cards, and an obvious contact-care-team action in the demo." },
  { category: "Technical attack", status: "pass", title: "The core can be demonstrated reliably", text: "A constrained source-to-card pipeline is practical with the team’s existing React and Python skills." },
  { category: "Scope attack", status: "critical", title: "Medication, symptoms and chat are too broad together", text: "Lead with medication clarification + red-flag check-ins. Make everything else stretch scope." },
];
